### ISSUE TITLE
Incorrect BlackPill product link

### ISSUE THREAD

**Issue by choryuidentify** [koendv/blackmagic-bluepill#3]
https://www.aliexpress.com/item/1005001456186625.html
This link contains 'AT32F403ACGU7' BlackPill, not an STmicro parts like 'stm32f144ceu6'.

**Comment by koendv** [comment]
Thank you.
This chip shortage is making everyone's lives a bit more difficult.

**Comment by choryuidentify** [comment]
> Thank you.
> This chip shortage is making everyone's lives a bit more difficult.
> 

Truly 🤣

**Comment by gbin** [comment]
yup bought the wrong ones out of this link lol ... would the port be hard for the AT32F403ACGU7? (I have no clue about the differences).

**Comment by koendv** [comment]
On Tue, 05 Jul 2022 05:36:00 -0700
Guillaume Binet ***@***.***> wrote:

> yup bought the wrong ones out of this link lol ... would the port be
> hard for the AT32F403ACGU7? (I have no clue about the differences).
> 

OK. Looks similar to a STM32F3xx to me, with the interesting addition of
external spi memory. 

Suggest try openocd first: https://review.openocd.org/c/openocd/+/5269

Maybe - I do not know - openocd has changed since the patch was
written.

(optional) Once you have it working on openocd, emit a vote on openocd
for the patch.

Then compile black magic probe, "hosted". This runs black magic probe
as a pc program, it is easier to debug.

Look at the patch for openocd, it says 
case 0x242: /* AT32F403 */
		page_size = 2048;
		stm32x_info->ppage_size = 2;
		max_flash_size_in_kb = 512;
		break;

So in black magic probe, you will need to patch file
blackmagic/src/target/stm32f1.c, in function stm32f1_probe(),
add a "case 0x242". It's black magic probe, so specify flash
"stm32f1_add_flash" and ram "target_add_ram". Something like that;
experiment. Read the user manual of the chip, and compare registers with
stm32f10x/stm32f30x, maybe it is similar. 

Once it works on black magic probe "hosted", compile for black magic
probe on blue pill. Ought to work. 

(Optional) Submit patch to black magic probe git.

best,

koen

**Comment by koendv** [comment]
On Tue, 5 Jul 2022 20:20:42 +0200
Koen De Vleeschauwer ***@***.***> wrote:

> Read the user manual of the chip,

This came out wrong. I don't mean you should read the *complete* user
manual. Just take a look at the registers of the flash controller, and
compare with stm32f10x/stm32f30x, and check you see similar registers
at the same addresses.

koen
